- name: prompt username and password
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: please enter your username
    private: false

  - name: password
    prompt: plase enter your password
    private: true

  tasks:
  - name: print info
    ansible.builtin.debug:
      msg: "username is {{ username }}, password is {{ password }}"
