- name: demo on filters
  hosts: local
  connection: local
  tasks:
  - name: Greetings
    ansible.builtin.debug:
     msg: " Hi, Chandu {{ GREETING | default('Good morning')}}" # here we passing variable as default and passing arguments in default as good morning