- name: Error handling demo
  hosts: local
  connection: local
  tasks:
   - name: checking the user exists
     ansible.builtin.command: id roboshop  # checking user roboshop is present or not using ansible.builtin.command
     register: user_output 

   - name: print output
     ansible.builtin.debug:
      msg: "{{ user_output }}"